### ISSUE TITLE
Cannot share file greater than 16M

### ISSUE THREAD

**Issue by cpickle** [shiyanhui/Young#5]
[E 170112 06:19:13 web:1548] Uncaught exception POST /share/new (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/share/new', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://localhost:8000', 'Content-Length': '21683702', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8000', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.20.3', 'Dnt': '1', 'Connection': 'Keep-Alive', 'Referer': 'http://localhost:8000/share', 'Cookie': 'session_id="2|1:0|10:1483999980|10:session_id|48:Yzg1NTk5ZWUtZDZiOC0xMWU2LWIwMmUtMDgwMDI3MDM1Yzk4|b5bb0d71a8f1bd6e31148873b9632a67e8aac861ca6c60858d9a3b0119faf428"; _xsrf=2|4063e675|754d976027562b150a302e0dbd8f9f15|1484004971', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundarywMTLPz4ycgNfEqbS'})
    Traceback (most recent call last):
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/web.py", line 1469, in _execute
        result = yield result
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/young/Young/app/share/handler.py", line 232, in post
        yield TemporaryFileDocument.insert(document)
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/home/young/Young/envs/main/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    DocumentTooLarge: BSON document too large (21681975 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.

**Comment by shiyanhui** [comment]
OK, I'll fix it later.

**Comment by cpickle** [comment]
Thanks for quick fix. it works now. 👍
